
export default todoActionTypes = {
    ADD_TODO : 'ADD_TODO',
    UPDATE_TODO : 'UPDATE_TODO',
    DELETE_TODO : 'DELETE_TODO',
    LOAD_TODO_DATA: 'LOAD_TODO_DATA',
    LOAD_TODO_SUCCESS: 'LOAD_TODO_SUCCESS',
    LOAD_TODO_FAILURE: 'LOAD_TODO_FAILURE',

}